### ISSUE TITLE
Problème pour faire marcher le plugin

### ISSUE THREAD

**Issue by Jiingo** [leomelki/LoupGarou#25]
Alors déjà merci d'occuper notre confinement 👍 mais pas pour moi :(

Mon problème est lorsque je me connecte à mon serveur privé il installe le pack et dis qu'il y a 1 joueur/26 donc moi mais je ne peux pas poser des blocs ni en casser donc pour faire la map directement moi même c'est pas possible, donc m'a première idée est de faire un /lg end mais là j'ai un internal error
`null
org.bukkit.command.CommandException: Unhandled exception executing command 'lg' in plugin LoupGarou v1.0.1
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[spigot.jar:git-Spigot-2ee05fe-d31f05f]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:149) ~[spigot.jar:git-Spigot-2ee05fe-d31f05f]
        at org.bukkit.craftbukkit.v1_15_R1.CraftServer.dispatchCommand(CraftServer.java:711) ~[spigot.jar:git-Spigot-2ee05fe-d31f05f]
        at net.minecraft.server.v1_15_R1.PlayerConnection.handleCommand(PlayerConnection.java:1657) ~[spigot.jar:git-Spigot-2ee05fe-d31f05f]
        at net.minecraft.server.v1_15_R1.PlayerConnection.a(PlayerConnection.java:1497) ~[spigot.jar:git-Spigot-2ee05fe-d31f05f]
        at net.minecraft.server.v1_15_R1.PacketPlayInChat.a(PacketPlayInChat.java:47) ~[spigot.jar:git-Spigot-2ee05fe-d31f05f]
        at net.minecraft.server.v1_15_R1.PacketPlayInChat.a(PacketPlayInChat.java:1) ~[spigot.jar:git-Spigot-2ee05fe-d31f05f]
        at net.minecraft.server.v1_15_R1.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:19) ~[spigot.jar:git-Spigot-2ee05fe-d31f05f]
        at net.minecraft.server.v1_15_R1.TickTask.run(SourceFile:18) [spigot.jar:git-Spigot-2ee05fe-d31f05f]
        at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeTask(SourceFile:144) [spigot.jar:git-Spigot-2ee05fe-d31f05f]
        at net.minecraft.server.v1_15_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) [spigot.jar:git-Spigot-2ee05fe-d31f05f]
        at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeNext(SourceFile:118) [spigot.jar:git-Spigot-2ee05fe-d31f05f]
        at net.minecraft.server.v1_15_R1.MinecraftServer.aZ(MinecraftServer.java:917) [spigot.jar:git-Spigot-2ee05fe-d31f05f]
        at net.minecraft.server.v1_15_R1.MinecraftServer.executeNext(MinecraftServer.java:910) [spigot.jar:git-Spigot-2ee05fe-d31f05f]
        at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.awaitTasks(SourceFile:127) [spigot.jar:git-Spigot-2ee05fe-d31f05f]
        at net.minecraft.server.v1_15_R1.MinecraftServer.sleepForTick(MinecraftServer.java:894) [spigot.jar:git-Spigot-2ee05fe-d31f05f]
        at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:827) [spigot.jar:git-Spigot-2ee05fe-d31f05f]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_211]
Caused by: java.lang.ArrayIndexOutOfBoundsException: 1
        at fr.leomelki.loupgarou.MainLg.onCommand(MainLg.java:228) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[spigot.jar:git-Spigot-2ee05fe-d31f05f]
        ... 17 more`

Voilà j’espère avoir une solution pour occuper le confinement si jamais il manque de détail il suffit de me le dire et j'essayerai d'aider. Merci ;)

**Comment by Nicooow** [comment]
Pour le /lg end il faut lire le README en entier, il faut faire /lg end [pseudo]
Ensuite pour les blocs c'est normal, le plugin empêche ça

**Comment by Jiingo** [comment]
Mais si je fais /lg end pseudo après je peux poser des blocs ?

**Comment by Commantary** [comment]
`/lg end pseudo` permet d’arrêter une partie en cours, si tu veux poser des blocs je te conseille d'enlever le plugin le temps que tu fasses ce que tu as à faire puis quand c'est bon tu remet le plugin

**Comment by Rigner** [comment]
Cette issue peut être fermée.
