### ISSUE TITLE
Incompatibilité Version Paper

### ISSUE THREAD

**Issue by LordThomDev** [leomelki/LoupGarou#37]
La quasi totalité des rôles ne marchent pas avec la version PAPER de Spigot. C'est bien dommage, paper augmente grandement la performance et la maniabilité des serveurs minecraft.

`[13:37:46] [Server thread/WARN]: [LoupGarou] Task #24 for LoupGarou v1.1.0 generated an exception
java.lang.ExceptionInInitializerError: null
	at fr.leomelki.loupgarou.roles.RLoupGarou.onNightTurn(RLoupGarou.java:89) ~[?:?]
	at fr.leomelki.loupgarou.classes.LGGame$7$1.run(LGGame.java:522) ~[?:?]
	at fr.leomelki.loupgarou.classes.LGGame$7$1.run(LGGame.java:519) ~[?:?]
	at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftTask.run(CraftTask.java:84) ~[spigot.jar:git-Paper-"9c2d9a5f"]
	at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:452) ~[spigot.jar:git-Paper-"9c2d9a5f"]
	at net.minecraft.server.v1_15_R1.MinecraftServer.b(MinecraftServer.java:1179) ~[spigot.jar:git-Paper-"9c2d9a5f"]
	at net.minecraft.server.v1_15_R1.DedicatedServer.b(DedicatedServer.java:417) ~[spigot.jar:git-Paper-"9c2d9a5f"]
	at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:1106) ~[spigot.jar:git-Paper-"9c2d9a5f"]
	at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:933) ~[spigot.jar:git-Paper-"9c2d9a5f"]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_144]
Caused by: java.lang.NullPointerException
	at net.minecraft.server.v1_15_R1.EntityLiving.<init>(EntityLiving.java:3344) ~[spigot.jar:git-Paper-"9c2d9a5f"]
	at net.minecraft.server.v1_15_R1.EntityArmorStand.<init>(EntityArmorStand.java:55) ~[spigot.jar:git-Paper-"9c2d9a5f"]
	at net.minecraft.server.v1_15_R1.EntityArmorStand.<init>(EntityArmorStand.java:69) ~[spigot.jar:git-Paper-"9c2d9a5f"]
	at fr.leomelki.loupgarou.classes.LGVote.<clinit>(LGVote.java:97) ~[?:?]
	... 10 more`

**Comment by codypl** [comment]
Si je ne dit pas de bétises, Paper créer un serveur en 1.15.2, hors le plugin est fait pour fonctionner en 1.15.1

**Comment by TimotheFCN** [comment]
Une toute petite modification au niveau de la déclaration des ArmorStand dans la classe LGVote a résolu le problème de mon côté, je vais faire un commit

**Comment by Rigner** [comment]
Cette issue peut être fermée.
