### ISSUE TITLE
Add Spawn error bug

### ISSUE THREAD

**Issue by Medkallel** [leomelki/LoupGarou#64]
Je suis sur Tlauncher et non pas sur la version officielle
Version 1.15 Forge
` Unexpected exception while parsing console command "lg addSpawn"
org.bukkit.command.CommandException: Unhandled exception executing command 'lg' in plugin LoupGarou v1.1.0
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[spigot.jar:git-Spigot-2ee05fe-d31f05f]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:149) ~[spigot.jar:git-Spigot-2ee05fe-d31f05f]
        at org.bukkit.craftbukkit.v1_15_R1.CraftServer.dispatchCommand(CraftServer.java:711) ~[spigot.jar:git-Spigot-2ee05fe-d31f05f]
        at org.bukkit.craftbukkit.v1_15_R1.CraftServer.dispatchServerCommand(CraftServer.java:696) [spigot.jar:git-Spigot-2ee05fe-d31f05f]
        at net.minecraft.server.v1_15_R1.DedicatedServer.handleCommandQueue(DedicatedServer.java:430) [spigot.jar:git-Spigot-2ee05fe-d31f05f]
        at net.minecraft.server.v1_15_R1.DedicatedServer.b(DedicatedServer.java:394) [spigot.jar:git-Spigot-2ee05fe-d31f05f]
        at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:978) [spigot.jar:git-Spigot-2ee05fe-d31f05f]
        at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:823) [spigot.jar:git-Spigot-2ee05fe-d31f05f]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_261]
Caused by: java.lang.ClassCastException: org.bukkit.craftbukkit.v1_15_R1.command.ColouredConsoleSender cannot be cast to org.bukkit.entity.Player
        at fr.leomelki.loupgarou.MainLg.onCommand(MainLg.java:222) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[spigot.jar:git-Spigot-2ee05fe-d31f05f]
        ... 8 more`

**Comment by leomelki** [comment]
Cette commande doit être exécutée a partir d'un joueur, pas de la console
