### ISSUE TITLE
Bug - Lancement de la partie 

### ISSUE THREAD

**Issue by LordThomDev** [leomelki/LoupGarou#9]
Lorsqu'une partie démarre, si un joueur déco le timer se stop, ce qui est normal.
Cependant lorsqu'il se reco sur la partie, tout les autres joueurs sont kick de la partie.

**Comment by leomelki** [comment]
As-tu bien utilisé **spigot** 1.15.1 ?

**Comment by LordThomDev** [comment]
Oui, le spigot ainsi que les joueurs sont en 1.15.1

**Comment by LordThomDev** [comment]
Après diverses recherches, je pense que c'est un problème de scoreboard, le joueur qui quite n'est pas retiré dans le plugin et crée des valeurs en trop, voici l'erreur que j'ai:

`13:22:44 [SEVERE] [LordThom] <-> DownstreamBridge <-> [LG] - encountered exception
java.lang.IllegalArgumentException: Team Thomdo already exists in this scoreboard
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:191)
	at net.md_5.bungee.api.score.Scoreboard.addTeam(Scoreboard.java:73)
	at net.md_5.bungee.connection.DownstreamBridge.handle(DownstreamBridge.java:210)
	at net.md_5.bungee.protocol.packet.Team.handle(Team.java:124)
	at net.md_5.bungee.netty.HandlerBoss.channelRead(HandlerBoss.java:105)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:377)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:355)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:377)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:355)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:377)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:355)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:321)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:295)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:377)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:355)
	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:377)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:355)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:377)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
	at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:792)
	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:475)
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:378)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at java.lang.Thread.run(Thread.java:748)v`

**Comment by MAXlME** [comment]
Yo j'ai le même problème et il s'avère que se bug est apparemment possible que lorsque l'on utilise un BungeeCord. Lorsqu'un joueur quitte après avoir jouer et qu'il revient son équipe est définit deux fois (du moins c'est ce que je pense) donc cela fait crash les autres joueurs... Voila ce que j'en est déduis. Donc probablement un problème venat du bungeecord puisque après des recherches je suis tombé sur des gens ayant le même problèmes mais sans continuité..
![Capture](https://user-images.githubusercontent.com/45951101/77235937-52796d00-6bba-11ea-945f-e48be0aa843a.PNG)

**Comment by LordThomDev** [comment]
Oui, je pense que lorsqu'un joueur quitte il n'est pas totalement supprimé des variables du plugin.
Je vais essayer de faire quelques recherche...

**Comment by MAXlME** [comment]
J'ai vérifié mais avant/après les parties aucunes équipes n'existes...

**Comment by leomelki** [comment]
Le plugin tel qu'il est actuellement n'est pas compatible avec bungeecord, il faudrait que je fasse une mise à jour pour fix ça

**Comment by LordThomDev** [comment]
Ce serait en effet génial si nous pouvions le mettre en bungeecord. 
Penses-tu en faire dans quelques jours ?
